### PR TITLE
Fix/#137 fix devtools

### LINKED ISSUE #137: React DevTools
It looks like the react devtools aren't working for me. I'm always getting the message about React being in production mode even though I load the react-tv.development.js. Tried it on the example project built by React-TV and got the same problem. 

Any idea how to fix this?

### PR DESCRIPTION
**Pull request by KevinMolotov**
Add version to React Devtools Injection to get the good buildType (prod/dev)

Fix #137

### CODE REVIEW

**Comment by raphamorim** [comment]
Thanks @KevinMolotov

File: packages/react-tv/renderer/ReactTVFiberEntry.js [hunk 1]
```diff
@@ -273,6 +273,7 @@ const ReactTVRenderer = {
 
     ReactTVFiberRenderer.injectIntoDevTools({
       bundleType: process.env.NODE_ENV === 'production' ? 0 : 1,
+      version: '0.4.4',
```
Comment (robolivable) [inline packages/react-tv/renderer/ReactTVFiberEntry.js]: Should we fetch this from `package.json`?

Comment (KevinMolotov) [reply packages/react-tv/renderer/ReactTVFiberEntry.js]: Yeah didn't thought about this, good idea!
