### PR TITLE
cli: updates runEmulator for Linux

### LINKED ISSUE #74: Failed to up virtualbox emulator
Hi @raphamorim,

I'm trying to start the LG WebOS Emulator 3.0.0 on Ubuntu 16.04 but I'm getting this error: 

screenshot from 2017-12-04 21-44-39

I've already followed the instructions in the react-tv docs to configure the WebOS Environment and the Emulator works fine when I run through the desktop icon.

Do you have any idea how to fix this error?

Thanks!

### PR DESCRIPTION
**Pull request by thiagommedeiros**
In Linux, we need to execute the `LG_webOS_TV_Emulator.sh` file to run the VirtualBox and the `LG_webOS_TV_Emulator_linux_x64.jar` file to run the remote control.

This PR also changes the `execSync` to `exec` child process method because the `LG_webOS_TV_Emulator_linux_x64.jar` blocks the command-line.

Closes #74

### CODE REVIEW

**Comment by raphamorim** [comment]
Nice @thiagommedeiros !

File: cli/scripts/webos/run.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const path = require('path');
 const fs = require('fs');
 const chalk = require('chalk');
+const exec = require('child_process').exec;
```
Comment (raphamorim) [inline cli/scripts/webos/run.js]: What do you think by replace this line and next one by:
```js
cons { exec, execSync } = require('child_process');
```

Comment (thiagommedeiros) [reply cli/scripts/webos/run.js]: Nice!!

**Comment by thiagommedeiros** [comment]
@raphamorim Done!

**Comment by raphamorim** [comment]
Thanks!!
